[licenses]
version = 2
private = { ignore = true }
confidence-threshold = 0.93 # We want really high confidence when inferring licenses from text
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Zlib"
]
exceptions = []

[bans]
multiple-versions = "allow"

[advisories]
ignore = ["RUSTSEC-2024-0436"] # Ignore because ratatui uses it