name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tarpaulin:
    name: Tarpaulin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Set up git user for tests
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI User"

      - name: Install cargo-tarpaulin
        uses: taiki-e/install-action@cargo-tarpaulin

      - name: Run coverage check
        run: cargo tarpaulin --workspace --all-features --fail-under 90 --out Xml --out Stdout
